name: zstd_ffi
description: zstd binding with ffi

version: 0.0.1
homepage: https://github.com/finlutter/zstd_ffi

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  
dev_dependencies:
  test:
  ffigen:

ffigen:
  name: "ZStd"
  description: "zstd ffi binding in Dart"
  output: "lib/_zstd.dart"
  headers:
    entry-points:
      - "lib/zstd.h"
