name: zstd_ffi
description: zstd ffi binding for Dart. More better performance than flutter plugin.

version: 0.0.3
homepage: https://github.com/finlutter/zstd_ffi

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  
dev_dependencies:
  test:
  ffigen:

ffigen:
  name: "ZStd"
  description: "zstd ffi binding in Dart"
  output: "lib/_zstd.dart"
  headers:
    entry-points:
      - "lib/zstd.h"
    include-directives:
      - "lib/zstd.h"
  comments: false
