name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # runs-on:  ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest,  windows-latest, macos-latest]

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: pwd; ls
    - name: Install dependencies
      run: pub get
    # - name: ffigen
    #   run: pub run ffigen
    - name: Run tests
      run: pub run test
